In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("DateFruit_dataset.csv")

In [4]:
df.head() # 34 features, 1 category

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
0,422163,2378.908,837.8484,645.6693,0.6373,733.1539,0.9947,424428,0.7831,1.2976,...,3.2370,2.9574,4.2287,-59191263232,-50714214400,-39922372608,58.7255,54.9554,47.8400,BERHI
1,338136,2085.144,723.8198,595.2073,0.5690,656.1464,0.9974,339014,0.7795,1.2161,...,2.6228,2.6350,3.1704,-34233065472,-37462601728,-31477794816,50.0259,52.8168,47.8315,BERHI
2,526843,2647.394,940.7379,715.3638,0.6494,819.0222,0.9962,528876,0.7657,1.3150,...,3.7516,3.8611,4.7192,-93948354560,-74738221056,-60311207936,65.4772,59.2860,51.9378,BERHI
3,416063,2351.210,827.9804,645.2988,0.6266,727.8378,0.9948,418255,0.7759,1.2831,...,5.0401,8.6136,8.2618,-32074307584,-32060925952,-29575010304,43.3900,44.1259,41.1882,BERHI
4,347562,2160.354,763.9877,582.8359,0.6465,665.2291,0.9908,350797,0.7569,1.3108,...,2.7016,2.9761,4.4146,-39980974080,-35980042240,-25593278464,52.7743,50.9080,42.6666,BERHI

In [5]:
df.sample(10)

,AREA,PERIMETER,MAJOR_AXIS,MINOR_AXIS,ECCENTRICITY,EQDIASQ,SOLIDITY,CONVEX_AREA,EXTENT,ASPECT_RATIO,...,KurtosisRR,KurtosisRG,KurtosisRB,EntropyRR,EntropyRG,EntropyRB,ALLdaub4RR,ALLdaub4RG,ALLdaub4RB,Class
31,314313,2040.2850,728.9534,550.9473,0.6548,632.6102,0.9943,316111,0.7460,1.3231,...,8.4980,12.5503,9.7957,-23896397824,-22137184256,-22064177152,43.6122,42.3951,41.0597,BERHI
180,144637,1422.4940,523.1910,352.5846,0.7388,429.1358,0.9905,146022,0.7623,1.4839,...,3.8348,3.2121,2.6395,-22750343168,-21672732672,-19304228864,61.7810,61.0920,57.3966,DOKOL
599,430797,2525.6411,933.5260,595.9404,0.7697,740.6131,0.9752,441741,0.7585,1.5665,...,2.5367,2.9489,2.1663,-50039312384,-42865414144,-51532402688,53.3630,49.9347,53.2723,ROTANA
829,253517,1860.3199,672.4048,483.4900,0.6950,568.1442,0.9912,255778,0.6885,1.3907,...,2.0166,2.0764,2.1188,-35527884800,-26220158976,-22443444224,56.1535,47.8068,44.3797,SOGAY
372,493734,2577.7070,919.6757,685.0148,0.6672,792.8693,0.9937,496873,0.7747,1.3426,...,7.4624,7.3636,5.2878,-28609906688,-31518064640,-33761247232,38.3052,39.9716,40.1476,IRAQI
673,340970,2301.7390,902.8800,483.9293,0.8442,658.8903,0.9895,344574,0.6506,1.8657,...,7.7035,7.3015,4.1894,-14205517824,-13602154496,-17087275008,30.4026,30.7527,36.0019,SAFAVI
817,310359,2138.5901,838.0970,472.3667,0.8260,628.6186,0.9892,313749,0.6902,1.7743,...,2.1734,2.1710,2.3246,-45976936448,-41103261696,-37712093184,59.4779,56.4527,54.8442,SOGAY
573,409795,2455.8789,846.9769,626.7124,0.6727,722.3345,0.9774,419259,0.6941,1.3515,...,2.6260,2.6896,2.5632,-63523319808,-54866644992,-43938672640,60.4733,57.0868,51.3920,ROTANA
608,345062,2668.8879,944.9453,468.3525,0.8685,662.8322,0.9694,355967,0.6318,2.0176,...,2.4313,2.9895,2.0872,-19990108160,-16136648704,-25802205184,36.3536,32.8508,41.3054,SAFAVI
57,392588,2274.2759,803.3082,625.8399,0.6269,707.0068,0.9973,393637,0.7623,1.2836,...,2.9783,4.9829,6.3596,-35574280192,-37579722752,-36809195520,47.4294,49.6277,48.6937,BERHI

In [6]:
df.isnull().sum()

AREA             0
PERIMETER        0
MAJOR_AXIS       0
MINOR_AXIS       0
ECCENTRICITY     0
EQDIASQ          0
SOLIDITY         0
CONVEX_AREA      0
EXTENT           0
ASPECT_RATIO     0
ROUNDNESS        0
COMPACTNESS      0
SHAPEFACTOR_1    0
SHAPEFACTOR_2    0
SHAPEFACTOR_3    0
SHAPEFACTOR_4    0
MeanRR           0
MeanRG           0
MeanRB           0
StdDevRR         0
StdDevRG         0
StdDevRB         0
SkewRR           0
SkewRG           0
SkewRB           0
KurtosisRR       0
KurtosisRG       0
KurtosisRB       0
EntropyRR        0
EntropyRG        0
EntropyRB        0
ALLdaub4RR       0
ALLdaub4RG       0
ALLdaub4RB       0
Class            0
dtype: int64

In [7]:
df.shape

(898, 35)

In [8]:
X = df.drop("Class", axis=1)
y = df["Class"]

In [10]:
df["Class"].unique()

array(['BERHI', 'DEGLET', 'DOKOL', 'IRAQI', 'ROTANA', 'SAFAVI', 'SOGAY'],
      dtype=object)

In [22]:
from sklearn.preprocessing import StandardScaler, LabelEncoder

le = LabelEncoder()
y = le.fit_transform(y)

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6])

In [25]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### ANN

In [26]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset

In [27]:
X_train_tensor = torch.tensor(X_train_scaled, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.long)

X_test_tensor = torch.tensor(X_test_scaled, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.long)

In [30]:
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

In [32]:
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=32)

In [41]:
# Build our Model

class ANN(nn.Module):
    def __init__(self):
        super(ANN, self).__init__()

        self.model = nn.Sequential(
            nn.Linear(X.shape[1], 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 7)
        )

    def forward(self, x):
        return self.model(x)

In [42]:
model = ANN()

# loss & optim
criteria = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters())

In [43]:
# Training the NN

epochs = 100
for epoch in range(epochs):
    model.train()

    running_loss = 0.0

    for xb, yb in train_loader:
        optimizer.zero_grad()
        
        outputs = model(xb)
        loss = criteria(outputs, yb)
        loss.backward()
        optimizer.step() # params update

        running_loss += loss

    train_loss = running_loss / len(train_loader)

    print(f"epoch = {epoch+1}/{epochs}, loss = {train_loss}")

epoch = 1/100, loss = 1.7222882509231567
epoch = 2/100, loss = 1.1361404657363892
epoch = 3/100, loss = 0.7546355128288269
epoch = 4/100, loss = 0.5427263379096985
epoch = 5/100, loss = 0.4281177818775177
epoch = 6/100, loss = 0.3639976978302002
epoch = 7/100, loss = 0.3230345845222473
epoch = 8/100, loss = 0.29712340235710144
epoch = 9/100, loss = 0.27281707525253296
epoch = 10/100, loss = 0.24977873265743256
epoch = 11/100, loss = 0.23040714859962463
epoch = 12/100, loss = 0.2229202687740326
epoch = 13/100, loss = 0.20380178093910217
epoch = 14/100, loss = 0.1951354295015335
epoch = 15/100, loss = 0.19549475610256195
epoch = 16/100, loss = 0.1741630584001541
epoch = 17/100, loss = 0.16832077503204346
epoch = 18/100, loss = 0.16172172129154205
epoch = 19/100, loss = 0.15662437677383423
epoch = 20/100, loss = 0.15177227556705475
epoch = 21/100, loss = 0.14764335751533508
epoch = 22/100, loss = 0.13652922213077545
epoch = 23/100, loss = 0.1390124261379242
epoch = 24/100, loss = 0.12697722017765045
epoch = 25/100, loss = 0.12620247900485992
epoch = 26/100, loss = 0.12762555480003357
epoch = 27/100, loss = 0.11508145183324814
epoch = 28/100, loss = 0.11708146333694458
epoch = 29/100, loss = 0.1199922263622284
epoch = 30/100, loss = 0.10734891891479492
epoch = 31/100, loss = 0.10498810559511185
epoch = 32/100, loss = 0.10322894901037216
epoch = 33/100, loss = 0.10000503808259964
epoch = 34/100, loss = 0.0959927961230278
epoch = 35/100, loss = 0.0933351069688797
epoch = 36/100, loss = 0.09356676042079926
epoch = 37/100, loss = 0.09025054425001144
epoch = 38/100, loss = 0.09697574377059937
epoch = 39/100, loss = 0.09231101721525192
epoch = 40/100, loss = 0.08339635282754898
epoch = 41/100, loss = 0.08216046541929245
epoch = 42/100, loss = 0.0789223164319992
epoch = 43/100, loss = 0.07768316566944122
epoch = 44/100, loss = 0.07759853452444077
epoch = 45/100, loss = 0.0750359296798706
epoch = 46/100, loss = 0.07315347343683243
epoch = 47/100, loss = 0.06933916360139847
epoch = 48/100, loss = 0.0722808986902237
epoch = 49/100, loss = 0.07111629843711853
epoch = 50/100, loss = 0.06638262420892715
epoch = 51/100, loss = 0.06340599805116653
epoch = 52/100, loss = 0.06052057072520256
epoch = 53/100, loss = 0.06021907553076744
epoch = 54/100, loss = 0.06148366257548332
epoch = 55/100, loss = 0.05861382931470871
epoch = 56/100, loss = 0.06600625813007355
epoch = 57/100, loss = 0.059680890291929245
epoch = 58/100, loss = 0.061150457710027695
epoch = 59/100, loss = 0.0545513741672039
epoch = 60/100, loss = 0.05848394334316254
epoch = 61/100, loss = 0.06230747327208519
epoch = 62/100, loss = 0.05242978036403656
epoch = 63/100, loss = 0.04607631266117096
epoch = 64/100, loss = 0.05189692601561546
epoch = 65/100, loss = 0.04470474645495415
epoch = 66/100, loss = 0.04719609394669533
epoch = 67/100, loss = 0.044130221009254456
epoch = 68/100, loss = 0.05276768282055855
epoch = 69/100, loss = 0.05576721951365471
epoch = 70/100, loss = 0.04265328869223595
epoch = 71/100, loss = 0.04270365834236145
epoch = 72/100, loss = 0.04209167882800102
epoch = 73/100, loss = 0.04367372393608093
epoch = 74/100, loss = 0.0382208451628685
epoch = 75/100, loss = 0.03763771057128906
epoch = 76/100, loss = 0.04204993695020676
epoch = 77/100, loss = 0.04101542383432388
epoch = 78/100, loss = 0.03304479271173477
epoch = 79/100, loss = 0.03361252695322037
epoch = 80/100, loss = 0.031882207840681076
epoch = 81/100, loss = 0.03288177028298378
epoch = 82/100, loss = 0.03229173645377159
epoch = 83/100, loss = 0.03090554289519787
epoch = 84/100, loss = 0.03234544396400452
epoch = 85/100, loss = 0.03166252747178078
epoch = 86/100, loss = 0.029081741347908974
epoch = 87/100, loss = 0.029864205047488213
epoch = 88/100, loss = 0.033028364181518555
epoch = 89/100, loss = 0.02880132384598255
epoch = 90/100, loss = 0.025719422847032547
epoch = 91/100, loss = 0.026626063510775566
epoch = 92/100, loss = 0.025836434215307236
epoch = 93/100, loss = 0.030673200264573097
epoch = 94/100, loss = 0.024868374690413475
epoch = 95/100, loss = 0.02299361117184162
epoch = 96/100, loss = 0.023217571899294853
epoch = 97/100, loss = 0.019978385418653488
epoch = 98/100, loss = 0.021561531350016594
epoch = 99/100, loss = 0.022461621090769768
epoch = 100/100, loss = 0.02030901238322258

In [47]:
# Evaluate
model.eval()

total = 0
correct = 0

with torch.no_grad():
    for xb, yb in test_loader:
        outputs = model(xb) # [0.2, 0.5, 1.3, -0.5, ..] -7 vals
        _, predicted = torch.max(outputs, 1)

        correct += (predicted == yb).sum().item()
        total += yb.size(0) # actual samples in each batch

print("accuracy: ", correct/total * 100)

accuracy:  95.0