In [96]:
import pandas as pd
import numpy as np

In [54]:
df = pd.read_csv("IMDB Dataset.csv")

In [55]:
df.shape

(50000, 2)

In [56]:
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [57]:
df.isnull().sum()

review       0
sentiment    0
dtype: int64

In [58]:
df.drop_duplicates(inplace=True)

In [59]:
df.shape

(49582, 2)

## Pre-processing

### 1. Converting to lowercase

In [60]:
df["review"] = df["review"].str.lower()

### 2. Removing the URLs

In [61]:
import re

# sample_text = "abc is the word, abc" # abc => xyz

# new_text = re.sub("abc", "xyz", sample_text)

In [62]:
def remove_urls(text):
    text = re.sub(r"https\S+" , "", text) # (pattern, repl, string)
    return text
    
df["review"] = df["review"].apply(remove_urls)

### 3. Removing punctuations

In [63]:
def remove_punctuations(text):
    text = re.sub(r"[^A-Za-z0-9\s]" , "", text) # A-Z a-z 0-9 \s
    return text

df["review"] = df["review"].apply(remove_punctuations)

### 4. Removing HTML

In [64]:
def remove_html(text):
    text = re.sub(r"<.*?>" , "", text)
    return text
    
df["review"] = df["review"].apply(remove_html)

### 5. Removing the Stopwords

In [65]:
import nltk

nltk.download("punkt")
nltk.download("punkt_tab")
nltk.download("stopwords")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\91778\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\91778\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\91778\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [66]:
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords

In [67]:
# sample_text = "I like coding in python!"
# tokens = word_tokenize(sample_text)

In [68]:
def remove_stopwords(text):
    tokens = word_tokenize(text)
    stop_words = stopwords.words("english")

    for word in tokens:
        if word in stop_words:
            text = text.replace(word, "")

    return text

df["review"] = df["review"].apply(remove_stopwords)

In [69]:
df.head()

                                              review sentiment
0  e    revewers  nted   wtchg  1 oz epode ll  ho...  positive
1   wderful ltle producti br br  filming techniqu...  positive
2   thought ths   wderful wy  spend tme   o hot s...  positive
3  bsclly res  fmly   lttle boy jke thks res  zom...  negative
4  petter mtte love   time  mey   vully stunng fi...  positive

### 6. Stemming

In [70]:
# running -> run
# played -> play
# PorterStemming

from nltk.stem import PorterStemmer

In [74]:
def stemming(text):
    ps = PorterStemmer()
    stemmed_words = []

    tokens = word_tokenize(text)
    for token in tokens:
        stemmed_token = ps.stem(token)
        stemmed_words.append(stemmed_token)

    return " ".join(stemmed_words)

df["review"] = df["review"].apply(stemming)

In [75]:
df.head()

                                              review sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...  positive
1  wder ltle producti br br film techniqu unssum ...  positive
2  thought th wder wy spend tme o hot summer week...  positive
3  bsclli re fmli lttle boy jke thk re zomb close...  negative
4  petter mtte love time mey vulli stunng film wt...  positive

### 7.Encoding

In [77]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

df["sentiment"] = le.fit_transform(df["sentiment"])

In [78]:
y = df["sentiment"]

In [79]:
y

0        1
1        1
2        1
3        0
4        1
        ..
49995    1
49996    0
49997    0
49998    0
49999    0
Name: sentiment, Length: 49582, dtype: int64

### 8. Vectorization

In [80]:
df.head()

                                              review  sentiment
0  e revew nted wtchg 1 oz epod ll hook y rght ex...          1
1  wder ltle producti br br film techniqu unssum ...          1
2  thought th wder wy spend tme o hot summer week...          1
3  bsclli re fmli lttle boy jke thk re zomb close...          0
4  petter mtte love time mey vulli stunng film wt...          1

In [83]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf = TfidfVectorizer(max_features=5000)

X = tf.fit_transform(df["review"])

In [84]:
X

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057158 stored elements and shape (49582, 5000)>

In [85]:
print(X)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4057158 stored elements and shape (49582, 5000)>
  Coords	Values
  (0, 3537)	0.05515484681268887
  (0, 2867)	0.09361182809242374
  (0, 4940)	0.11467310366614668
  (0, 3001)	0.47200539890110405
  (0, 1275)	0.1357698919196183
  (0, 2288)	0.049500237517476293
  (0, 1932)	0.0791260308382
  (0, 3549)	0.0963974330192639
  (0, 1361)	0.06162489377343992
  (0, 1962)	0.061560444992697486
  (0, 219)	0.08588920995304898
  (0, 1619)	0.0738170550485134
  (0, 4368)	0.041994187696759305
  (0, 4170)	0.17799685402440263
  (0, 3692)	0.033532198172897175
  (0, 4737)	0.26798942924092045
  (0, 3804)	0.04427609784380831
  (0, 4769)	0.05877405881441711
  (0, 1738)	0.037520883911174724
  (0, 4496)	0.07614066339174266
  (0, 3856)	0.17537900435282314
  (0, 1629)	0.06142445471882175
  (0, 1861)	0.07433134577032253
  (0, 3328)	0.06406818508428483
  (0, 3331)	0.0844754682576354
  :	:
  (49581, 4890)	0.10682334916138103
  (49581, 1541)	0.17584072573791829
  (49581, 4493)	0.09410069396961679
  (49581, 435)	0.11251655954741112
  (49581, 4276)	0.10905956327445408
  (49581, 1957)	0.0999074542943991
  (49581, 555)	0.08424218838425554
  (49581, 2186)	0.14180348667063264
  (49581, 2216)	0.09535602544797335
  (49581, 4346)	0.17508214877875983
  (49581, 4629)	0.1157123083349983
  (49581, 3646)	0.087334023293812
  (49581, 4734)	0.12354122837064464
  (49581, 1976)	0.1279546327938257
  (49581, 527)	0.1247934452922504
  (49581, 2620)	0.17341357547872566
  (49581, 4457)	0.16002233459530202
  (49581, 2173)	0.18983797727912208
  (49581, 4032)	0.20100044911463438
  (49581, 342)	0.14784964476913964
  (49581, 2694)	0.1740080872946952
  (49581, 440)	0.13323526536564564
  (49581, 4980)	0.15095820717373318
  (49581, 1763)	0.15815315432712562
  (49581, 3488)	0.1519741559925848

## Dataset & Data Loaders

In [86]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [87]:
X_train.shape

(39665, 5000)

In [88]:
X_test.shape

(9917, 5000)

In [93]:
import torch
from torch.utils.data import TensorDataset, DataLoader

In [94]:
X_train

array([[0.2133337, 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       ...,
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ],
       [0.       , 0.       , 0.       , ..., 0.       , 0.       ,
        0.       ]])

In [97]:
X_train = X_train.toarray()
X_test = X_test.toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [98]:
train_set = TensorDataset(
    torch.from_numpy(X_train).float(),
    torch.from_numpy(y_train.values).float(),
)

test_set = TensorDataset(
    torch.from_numpy(X_test).float(),
    torch.from_numpy(y_test.values).float(),
)

In [99]:
train_loader = DataLoader(train_set, shuffle=True, batch_size=64)
test_loader = DataLoader(test_set, shuffle=True, batch_size=64)

## Build our RNN

In [104]:
import torch.nn as nn
import torch.optim as optim

In [105]:
class RNN(nn.Module):
    def __init__(self, input_size, hidden_size=128, num_layers=1):
        super().__init__()

        self.hidden_size = hidden_size
        self.num_layers = num_layers

        # RNN layer
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)

        # fully connected layer
        self.fc = nn.Linear(hidden_size, 1)

    def forward(self, x):
        # optional => shape (num of layers, batch size, hidden size)
        h0 = torch.zeros(self.num_layers, x.size(0), self.hidden_size)

        out, _ = self.rnn(x, h0) 
        # 1st value =  hidden state of all the timesteps => (batch, seq_len, hidden size)
        # 2nd value = final hidden state of last timestep

        out = self.fc(out[:, -1, :])
        return out

In [106]:
input_size = X_train.shape[1]

model = RNN(input_size)

criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters())

## Training the RNN

In [111]:
epochs = 10

for epoch in range(epochs):
    model.train()

    for Xb, yb in train_loader:
        optimizer.zero_grad()

        Xb = Xb.unsqueeze(1) # add singleton direction

        outputs = model(Xb) # (batch_size, 1)

        outputs = torch.sigmoid(outputs) # (batch-size,) => probability

        loss = criterion(outputs, yb.unsqueeze(1).float()) # compute loss

        loss.backward() # backprop
        optimizer.step() # weights update

    print(f"epoch = {epoch}/{epochs} and loss = {loss.item()}")

epoch = 0/10 and loss = 0.2263108789920807
epoch = 1/10 and loss = 0.18471570312976837
epoch = 2/10 and loss = 0.33109092712402344
epoch = 3/10 and loss = 0.1889687329530716
epoch = 4/10 and loss = 0.3501471281051636
epoch = 5/10 and loss = 0.46578142046928406
epoch = 6/10 and loss = 0.19090677797794342
epoch = 7/10 and loss = 0.2266090363264084
epoch = 8/10 and loss = 0.12165983021259308
epoch = 9/10 and loss = 0.24844574928283691

In [113]:
# evaluate

model.eval()

with torch.no_grad():
    correct_vals = 0
    tot_vals = 0

    for Xb, yb in test_loader:
        Xb = Xb.unsqueeze(1)

        outputs = model(Xb)
        predicted = (torch.sigmoid(outputs.squeeze()) > 0.5).float()

        tot_vals += yb.size(0)
        correct_vals += (predicted == yb).sum().item()

    print(f"accuracy = {correct_vals/tot_vals*100}")

accuracy = 85.63073510134113